MIN_MONSTERS = 4
MAX_MONSTERS = 4
OPEN_BAGS = true 

function move()
          return {
        { map = "4,-19", path = "bottom" },
        { map = "4,-18", path = "bottom" },
        { map = "4,-17", path = "bottom" },
          { map="2,-12", path = "top" },
        { map = "-1,-14", path = "bottom" },
{ map = "-1,-15", path = "bottom" },
{ map = "-1,-16", path = "bottom" },
{ map = "-1,-17", path = "bottom" },	
{ map = "0,-19", path = "left" },	
{ map = "-1,-19", path = "bottom" },	
{ map = "-1,-18", path = "bottom" },	
{ map = "1,-21", path = "bottom" },
{ map = "1,-20", path = "left" },
{ map = "-1,-20", path = "left" },
{ map = "0,-20", path = "left" },
{ map = "1,-22", path = "bottom" },
{ map = "2,-22", path = "left" },
{ map = "2,-20", path = "right" },
{ map = "3,-16", path = "right" },
{ map = "84675079", path = "top" },
{ map = "83886090", door = "465" },
{ map = "6,-16", path = "left" },
{ map = "7,-16", path = "left" },
{ map = "7,-15", path = "top" },
{ map = "7,-17", path = "bottom" },
{ map = "6,-20", path = "left" },
{ map = "7,-21", path = "left" },
{ map = "6,-21", path = "left" },
        { map="4,-3", custom = npctoastrub },
        { map = "84674051", path = "right" },
        { map = "153092354", door = "409" },
        { map = "152046597", path = "right" },
        { map = "-2,-3", path = "right" },
        { map = "-1,-3", path = "right" },
        { map = "0,-3", path = "right" },
        { map = "1,-3", path = "right" },
        { map = "2,-3", path = "right" },
        { map = "3,-3", path = "right" },
        { map = "5,-21", path = "top" },
        { map = "5,-20", path = "top" },
        { map = "5,-19", path = "top" },
        { map = "5,-18", path = "top" },
        { map = "5,-17", path = "top" },
        { map = "5,-16", path = "top" },
        { map = "5,-22", path = "top" },
        { map = "4,-22", path = "right" },
        { map = "3,-22", path = "right" },
        { map = "3,-21", path = "top" },
        { map = "3,-20", path = "top" },
        { map = "3,-19", path = "top" },
        { map = "7,-22", path = "top|left|right", fight = true },
        { map = "6,-22", path = "top|right", fight = true },
        { map = "6,-23", path = "left|right|bottom", fight = true },
        { map = "7,-23", path = "left|right|bottom", fight = true },
        { map = "8,-23", path = "left|bottom", fight = true },
        { map = "8,-22", path = "top|left|bottom", fight = true },
        { map = "8,-21", path = "top|bottom", fight = true },
        { map = "8,-20", path = "top|bottom", fight = true },
        { map = "8,-19", path = "top|bottom", fight = true },
        { map = "8,-18", path = "top|bottom", fight = true },
        { map = "8,-17", path = "top|bottom", fight = true },
        { map = "8,-16", path = "top|bottom", fight = true },
        { map = "8,-15", path = "top|bottom", fight = true },
        { map = "8,-14", path = "top|left|bottom", fight = true },
        { map = "7,-13", path = "top|left|right", fight = true },
        { map = "7,-14", path = "left|right|bottom", fight = true },
        { map = "6,-14", path = "left|right|bottom", fight = true },
        { map = "5,-14", path = "right|bottom", fight = true },
        { map = "8,-13", path = "top|left", fight = true },
        { map = "6,-13", path = "top|left|right", fight = true },
        { map = "5,-13", path = "top|left|right", fight = true },
        { map = "4,-13", path = "left|right", fight = true },
        { map = "3,-13", path = "left|right", fight = true },
        { map = "2,-13", path = "left|right", fight = true },
        { map = "1,-13", path = "left|right", fight = true },
        { map = "0,-13", path = "left|right", fight = true },
        { map = "-1,-13", path = "left|right", fight = true },
        { map = "-2,-17", path = "top|left|bottom", fight = true },
        { map = "-2,-19", path = "top|left|bottom", fight = true },
        { map = "-2,-18", path = "top|left|bottom", fight = true },
        { map = "-2,-16", path = "top|left|bottom", fight = true },
        { map = "-2,-15", path = "top|left|bottom", fight = true },
        { map = "-2,-14", path = "top|left|bottom", fight = true },
        { map = "-2,-13", path = "top|left|right", fight = true },
        { map = "-3,-13", path = "top|right", fight = true },
        { map = "-3,-14", path = "top|right|bottom", fight = true },
        { map = "-3,-15", path = "top|right|bottom", fight = true },
        { map = "-3,-16", path = "top|right|bottom", fight = true },
        { map = "-3,-17", path = "top|right|bottom", fight = true },
        { map = "-3,-18", path = "top|right|bottom", fight = true },
        { map = "-3,-19", path = "top|right|bottom", fight = true },
        { map = "-3,-20", path = "right|bottom", fight = true },
        { map = "-2,-20", path = "top|left|bottom", fight = true },
        { map = "-2,-21", path = "top|bottom", fight = true },
        { map = "-2,-22", path = "top|right|bottom", fight = true },
        { map = "-2,-23", path = "right|bottom", fight = true },
        { map = "-1,-22", path = "top|left", fight = true },
        { map = "-1,-23", path = "left|right|bottom", fight = true },
        { map = "0,-23", path = "left|right", fight = true },
        { map = "1,-23", path = "left|right", fight = true },
        { map = "2,-23", path = "left|right", fight = true },
        { map = "3,-23", path = "left|right", fight = true },
        { map = "4,-23", path = "left|right", fight = true },
        
        { map = "5,-23", path = "left|right", fight = true },
        { map = "84674566", path = "right" },
        { map = "83887104", path = "396" },
    }
end


function bank()
    return {

        { map = "5,-21",     path = "bottom" },
        { map = "5,-22",     path = "bottom" },
        { map = "5,-23",     path = "bottom" },
        { map = "5,-20",     path = "bottom" },
        { map = "5,-19",     path = "bottom" },
        { map = "5,-17",     path = "bottom" },
        { map = "5,-18",     path = "bottom" },
        { map = "5,-16",     path = "left" }
    }
end

function phenix()
    return {

    }
end