
MAX_PODS = 90 
MIN_MONSTERS = 4
MIN_MONSTERS = 4
MIN_LIFE = 70


function move()
	return {
		{ map="-47,14", fight = true, path = "right" },
		{ map="-46,14", fight = true, path = "top" },
		{ map="-46,13", fight = true, path = "left" },
		{ map="-47,13", fight = true, path = "top" },
		{ map="-47,12", fight = true, path = "top|left" },
		{ map="-47,11", fight = true, path = "left" },
		{ map="-48,12", fight = true, path = "top" },
		{ map="-48,11", fight = true, path = "top" },
		{ map="-48,10", fight = true, path = "top" },
		{ map="-48,9", fight = true, path = "left" },
		{ map="-49,9", fight = true, path = "top" },
		{ map="-49,8", fight = true, path = "left" },
		{ map="-50,8", fight = true, path = "top" },
		{ map="-50,7", fight = true, path = "left" },
		{ map="-51,7", fight = true, path = "top" },
		{ map="-51,6", fight = true, path = "right" },
		{ map="-50,6", fight = true, path = "top" },
		{ map="-50,5", fight = true, path = "left" },
		{ map="-51,5", fight = true, path = "left" },
		{ map="-52,5", fight = true, path = "top" },
		{ map="-52,4", fight = true, path = "right" },
		{ map="-51,4", fight = true, path = "top" },
		{ map="-51,3", fight = true, path = "left" },
		{ map="-52,3", fight = true, path = "top" },
		{ map="-52,2", fight = true, path = "top" },
		{ map="-52,1", fight = true, path = "top" },
		{ map="-52,0", fight = true, path = "top" },
		{ map="-52,-1", fight = true, path = "left" },
		{ map="-53,-1", fight = true, path = "bottom" },
		{ map="-53,0", fight = true, path = "bottom" },
		{ map="-53,1", fight = true, path = "bottom" },
		{ map="-53,2", fight = true, path = "left" },
		{ map="-54,2", fight = true, path = "top" },
		{ map="-54,1", fight = true, path = "top" },
		{ map="-54,0", fight = true, path = "left" },
		{ map="-55,0", fight = true, path = "bottom" },
		{ map="-55,1", fight = true, path = "bottom" },
		{ map="-55,2", fight = true, path = "left" },
		{ map="-56,2", fight = true, path = "left" },
		{ map="-57,2", fight = true, path = "top" },
		{ map="-57,1", fight = true, path = "left" },
		{ map="-58,1", fight = true, path = "bottom" },
		{ map="-58,2", fight = true, path = "bottom" },
		{ map="-58,3", fight = true, path = "left" },
		{ map="-59,3", fight = true, path = "bottom" },
		{ map="-59,4", fight = true, path = "right" },
		{ map="-58,4", fight = true, path = "bottom" },
		{ map="-58,5", fight = true, path = "left" },
		{ map="-58,7", fight = true, path = "left" },
		{ map="-58,9", fight = true, path = "left" },
		{ map="-58,11", fight = true, path = "left" },
		{ map="-58,13", fight = true, path = "left" },
		{ map="-58,15", fight = true, path = "left" },
		{ map="-58,17", fight = true, path = "left" },
		{ map="-58,19", fight = true, path = "left" },
		{ map="-58,21", fight = true, path = "left" },
		{ map="-59,5", fight = true, path = "bottom" },
		{ map="-59,7", fight = true, path = "bottom" },
		{ map="-59,9", fight = true, path = "bottom" },
		{ map="-59,11", fight = true, path = "bottom" },
		{ map="-59,13", fight = true, path = "bottom" },
		{ map="-59,15", fight = true, path = "bottom" },
		{ map="-59,17", fight = true, path = "bottom" },
		{ map="-59,19", fight = true, path = "bottom" },
		{ map="-59,21", fight = true, path = "bottom" },
		{ map="-58,6", fight = true, path = "bottom" },
		{ map="-58,8", fight = true, path = "bottom" },
		{ map="-58,10", fight = true, path = "bottom" },
		{ map="-58,12", fight = true, path = "bottom" },
		{ map="-58,14", fight = true, path = "bottom" },
		{ map="-58,16", fight = true, path = "bottom" },
		{ map="-58,18", fight = true, path = "bottom" },
		{ map="-58,20", fight = true, path = "bottom" },
		{ map="-58,22", fight = true, path = "bottom" },
		{ map="-58,23", fight = true, path = "bottom" },
		{ map="-59,6", fight = true, path = "right" },
		{ map="-59,8", fight = true, path = "right" },
		{ map="-59,10", fight = true, path = "right" },
		{ map="-59,12", fight = true, path = "right" },
		{ map="-59,14", fight = true, path = "right" },
		{ map="-59,16", fight = true, path = "right" },
		{ map="-59,18", fight = true, path = "right" },
		{ map="-59,20", fight = true, path = "right" },
		{ map="-59,22", fight = true, path = "right" },
		{ map="-58,24", fight = true, path = "right" },
		{ map="-57,24", fight = true, path = "bottom" },
		{ map="-57,25", fight = true, path = "bottom" },
		{ map="-57,26", fight = true, path = "right" },
		{ map="-56,26", fight = true, path = "top" },
		{ map="-56,24", fight = true, path = "right" },
		{ map="-55,25", fight = true, path = "right" },
		{ map="-55,24", fight = true, path = "bottom" },
		{ map="-56,25", fight = true, path = "top" },
		{ map="-54,25", fight = true, path = "top" },
		{ map="-54,24", fight = true, path = "right" },
		{ map="-53,24", fight = true, path = "right" },
		{ map="-52,24", fight = true, path = "right" },
		{ map="-51,24", fight = true, path = "top" },
		{ map="-51,23", fight = true, path = "right" },
		{ map="-50,23", fight = true, path = "top" },
		{ map="-50,22", fight = true, path = "right" },
		{ map="-49,22", fight = true, path = "top" },
		{ map="-49,21", fight = true, path = "top" },
		{ map="-49,19", path = "top" },
		{ map="-49,20", path = "top" },
		{ map="-49,18", path = "top" },
		{ map="-49,17", path = "top" },
		{ map="-49,16", path = "top" },
		{ map="-49,15", path = "top" },
		{ map="-49,14", path = "right" },
		{ map="-48,14", path = "right" },
		{ map="-47,15", path = "top" },
		{ map="-47,18", path = "top" },
		{ map="-47,17", path = "top" },
		{ map="-47,16", path = "top" },
		{ map="-46,18", path = "left" },
	
	}
	
end


