function ASTRUB()
    npc:npc(888, 3) 
	global:delay(500)
    npc:reply(-1)
	global:delay(500)
    npc:reply(-1)
	global:delay(500)
	npc:reply(-1)
	global:delay(500)
	npc:leaveDialog()
end

AUTO_DELETE = {11250 , 11254 ,11257 ,11256 ,11255,11475,11253,6897,6898,6899,6903,6900,6902,6901,2584,2585 }

function frifri()
    npc:npc(1236, 3)
    npc:reply(-1)
    npc:leaveDialog()
    global:delay(500)
end

function fri()
    npc:npc(1236, 3)
    npc:leaveDialog()
end

function equip1()
 inventory:equipItem(2474,6) --Chapeau
 inventory:equipItem(2473,7) --Cape
 inventory:equipItem(2476,5) --Bottes
 inventory:equipItem(2475,2) --Anneau
 inventory:equipItem(2477,3) --Ceinture
 inventory:equipItem(2478,0) --Amulette
global:printSuccess("PANO Aventurier ok")
end
function equip2()
 inventory:equipItem(6926,6) --Chapeau prespic
 inventory:equipItem(6927,7) --Cape prespic
 inventory:equipItem(2374,5) --Bottes tarsy
 inventory:equipItem(732,2) --Alliance Silimelle
  inventory:equipItem(732,4) --Alliance Silimelle
 inventory:equipItem(1487,3) --L'Adelus
 inventory:equipItem(1489,0) --Broche Hète
 global:printSuccess("PANO SAGESSE ok")
end
function equip3()
   inventory:equipItem(8463,6) --Abracaska Ancestral  
 inventory:equipItem(8464,7) --Abracapa Ancestrale
 inventory:equipItem(8467,5) -- Protège-Tibias Ancestraux
 inventory:equipItem(8466,2) -- Anneau Ancestral
 inventory:equipItem(8468,3) --Abrature Ancestrale
 inventory:equipItem(8465,0) -- Torque Ancestral
  global:printSuccess("PANOPLIE ANCESTRALE ok")
end

function move()
  if character:level() >= 1 and character:level() < 9 then
    return Piou()
    elseif character:level() >= 9 and character:level() < 15 then
    return piou2()
  elseif character:level() >= 15 and character:level() < 36 then
    return piou3()
    elseif character:level() >= 36 and character:level() < 114 then
    return boo()
    elseif character:level() >= 114 and character:level() < 200 then
    return frigost()
  end
end

function Piou()
  MIN_MONSTERS = 1
  MAX_MONSTERS = 1
  AUTO_DELETE = {} 
  return {
      { map = "-5,-1", path = "bottom" },
        { map = "-4,0", path = "right" },
        { map = "-3,1", path = "right" },
        { map = "-2,2", path = "bottom" },

        { map = "81264644", path = "bottom" },
        { map = "81268739", path = "right" },
        { map = "81269763", path = "right" },
        { map = "81270787", path = "bottom" },

   { map = "0,3", path = "right" },
   { map = "1,3", path = "right" },
   { map = "2,3", path = "right" },
   { map = "3,3", path = "right" },
   { map = "4,3", path = "right" },
   { map = "5,3", path = "right" },
   { map = "6,3", path = "right" },
   { map = "7,3", path = "right" },
   { map = "8,3", custom=equip1, path = "right" },
   { map = "9,3", custom =ASTRUB },

   { map = "-2,-20", path = "right" },
   { map = "8,-19", path = "left" },
   { map = "7,-19", path = "left" },
   { map = "5,-23", path = "bottom" },
   { map = "5,-22", path = "bottom" },
   { map = "4,-14", path = "top" },
   { map = "4,-15", path = "top" },
   { map = "-2,-24", path = "bottom" },
   { map = "-2,-23", path = "bottom" },
   { map = "-2,-22", path = "bottom" },
   { map = "-2,-21", path = "bottom" },
   { map = "5,-24", path = "bottom" },
   { map = "5,-25", path = "bottom" },
   { map = "5,-26", path = "bottom" },
   { map = "5,-27", path = "bottom" },
   { map = "4,-27", path = "bottom" },
   { map = "3,-27", path = "bottom" },
   { map = "2,-27", path = "bottom" },
   { map = "1,-27", path = "bottom" },
   { map = "0,-27", path = "bottom" },
   { map = "0,-26", path = "bottom" },
   { map = "-1,-26", path = "bottom" },
   { map = "-1,-27", path = "bottom" },
   { map = "-2,-27", path = "bottom" },
   { map = "-2,-26", path = "bottom" },
   { map = "-2,-25", path = "bottom" },
   { map = "-1,-25", path = "bottom" },
   { map = "0,-25", path = "bottom" },
   { map = "1,-25", path = "bottom" },
   { map = "1,-26", path = "bottom" },
   { map = "2,-26", path = "bottom" },
   { map = "2,-25", path = "bottom" },
   { map = "3,-25", path = "bottom" },
   { map = "3,-26", path = "bottom" },
   { map = "4,-26", path = "bottom" },
   { map = "4,-25", path = "bottom" },
   { map = "4,-24", path = "bottom" },
   { map = "3,-24", path = "bottom" },
   { map = "2,-24", path = "bottom" },
   { map = "1,-24", path = "bottom" },
   { map = "0,-24", path = "bottom" },
   { map = "-1,-24", path = "bottom" },
   { map = "2,-23", path = "left" },
   { map = "0,-23", path = "left" },
   { map = "1,-23", path = "left" },
   { map = "-1,-23", path = "left" },
   { map = "-1,-22", path = "left" },
   { map = "3,-23", path = "right" },
   { map = "4,-23", path = "right" },
   { map = "8,-23", path = "left" },
   { map = "6,-23", path = "left" },
   { map = "7,-23", path = "left" },
   { map = "8,-24", path = "left" },
   { map = "8,-25", path = "left" },
   { map = "7,-25", path = "left" },
   { map = "7,-26", path = "left" },
   { map = "7,-27", path = "left" },
   { map = "6,-27", path = "left" },
   { map = "6,-25", path = "left" },
   { map = "6,-26", path = "left" },
   { map = "6,-24", path = "left" },
   { map = "7,-24", path = "left" },
   { map = "11,-19", path = "left" },
   { map = "11,-20", path = "left" },
   { map = "11,-21", path = "left" },
   { map = "11,-22", path = "left" },
   { map = "10,-22", path = "left" },
   { map = "9,-22", path = "left" },
   { map = "8,-22", path = "left" },
   { map = "10,-21", path = "left" },
   { map = "9,-21", path = "left" },
   { map = "10,-20", path = "left" },
   { map = "9,-20", path = "left" },
   { map = "10,-19", path = "left" },
   { map = "9,-19", path = "left" },
   { map = "11,-17", path = "left" },
   { map = "11,-18", path = "left" },
   { map = "11,-16", path = "left" },
   { map = "11,-15", path = "left" },
   { map = "12,-15", path = "left" },
   { map = "13,-15", path = "left" },
   { map = "12,-16", path = "left" },
   { map = "12,-17", path = "left" },
   { map = "12,-18", path = "left" },
   { map = "12,-19", path = "left" },
   { map = "12,-20", path = "left" },
   { map = "12,-21", path = "left" },
   { map = "12,-22", path = "left" },
   { map = "10,-15", path = "left" },
   { map = "9,-15", path = "left" },
   { map = "10,-16", path = "left" },
   { map = "9,-16", path = "left" },
   { map = "10,-17", path = "left" },
   { map = "9,-17", path = "left" },
   { map = "10,-18", path = "left" },
   { map = "9,-18", path = "left" },
   { map = "8,-15", path = "top" },
   { map = "8,-16", path = "top" },
   { map = "8,-17", path = "top" },
   { map = "8,-18", path = "top" },
   { map = "8,-21", path = "bottom" },
   { map = "8,-20", path = "bottom" },
   { map = "7,-22", path = "top" },
   { map = "6,-22", path = "top" },
   { map = "7,-9", path = "top" },
   { map = "6,-9", path = "top" },
   { map = "5,-9", path = "top" },
   { map = "4,-9", path = "top" },
   { map = "3,-9", path = "top" },
   { map = "2,-9", path = "top" },
   { map = "2,-10", path = "top" },
   { map = "2,-11", path = "top" },
   { map = "2,-12", path = "top" },
   { map = "3,-12", path = "top" },
   { map = "4,-12", path = "top" },
   { map = "5,-12", path = "top" },
   { map = "6,-12", path = "top" },
   { map = "7,-12", path = "top" },
   { map = "8,-12", path = "top" },
   { map = "9,-12", path = "top" },
   { map = "10,-12", path = "top" },
   { map = "11,-12", path = "top" },
   { map = "11,-13", path = "top" },
   { map = "11,-14", path = "top" },
   { map = "10,-13", path = "top" },
   { map = "10,-14", path = "top" },
   { map = "9,-13", path = "left" },
   { map = "9,-14", path = "left" },
   { map = "8,-14", path = "left" },
   { map = "7,-14", path = "left" },
   { map = "6,-14", path = "left" },
   { map = "5,-14", path = "left" },
   { map = "8,-13", path = "left" },
   { map = "7,-13", path = "left" },
   { map = "6,-13", path = "left" },
   { map = "5,-13", path = "left" },
   { map = "9,-11", path = "left" },
   { map = "10,-11", path = "left" },
   { map = "11,-11", path = "left" },
   { map = "10,-10", path = "left" },
   { map = "9,-10", path = "left" },
   { map = "9,-9", path = "left" },
   { map = "8,-9", path = "left" },
   { map = "8,-10", path = "left" },
   { map = "8,-11", path = "left" },
   { map = "7,-11", path = "left" },
   { map = "7,-10", path = "left" },
   { map = "6,-10", path = "left" },
   { map = "6,-11", path = "left" },
   { map = "5,-11", path = "left" },
   { map = "5,-10", path = "left" },
   { map = "4,-10", path = "top" },
   { map = "4,-11", path = "top" },
   { map = "4,-13", path = "top" },
   { map = "3,-10", path = "right" },
   { map = "3,-11", path = "right" },
   { map = "3,-13", path = "right" },
   { map = "2,-13", path = "right" },
   { map = "1,-13", path = "right" },
   { map = "0,-13", path = "right" },
   { map = "-1,-13", path = "right" },
   { map = "-2,-13", path = "right" },
   { map = "-2,-12", path = "right" },
   { map = "-1,-12", path = "right" },
   { map = "0,-12", path = "right" },
   { map = "1,-12", path = "right" },
   { map = "1,-11", path = "right" },
   { map = "-1,-11", path = "right" },
   { map = "-2,-11", path = "right" },
   { map = "0,-11", path = "right" },
   { map = "1,-10", path = "right" },
   { map = "0,-10", path = "right" },
   { map = "-1,-10", path = "right" },
   { map = "-2,-10", path = "right" },
   { map = "1,-9", path = "right" },
   { map = "-4,-14", path = "right" },
   { map = "-3,-14", path = "right" },
   { map = "-2,-14", path = "right" },
   { map = "-3,-13", path = "right" },
   { map = "-4,-13", path = "right" },
   { map = "-4,-15", path = "right" },
   { map = "-4,-16", path = "right" },
   { map = "-4,-17", path = "right" },
   { map = "-4,-18", path = "right" },
   { map = "-4,-20", path = "right" },
   { map = "-4,-19", path = "right" },
   { map = "-4,-21", path = "right" },
   { map = "-5,-23", path = "right" },
   { map = "-4,-22", path = "right" },
   { map = "-4,-23", path = "right" },
   { map = "-3,-23", path = "right" },
   { map = "-3,-22", path = "right" },
   { map = "-3,-21", path = "right" },
   { map = "-2,-18", path = "top" },
   { map = "-3,-19", path = "top" },
   { map = "-2,-19", path = "top" },
   { map = "-3,-18", path = "top" },
   { map = "-3,-20", path = "right" },
   { map = "-2,-17", path = "bottom" },
   { map = "-2,-16", path = "bottom" },
   { map = "-2,-15", path = "bottom" },
   { map = "-3,-15", path = "bottom" },
   { map = "-3,-16", path = "bottom" },
   { map = "-3,-17", path = "bottom" },
   { map = "5,-21", path = "bottom" },
   { map = "5,-20", path = "bottom" },
   { map = "5,-19", path = "bottom" },
   { map = "5,-18", path = "bottom" },
   { map = "5,-17", path = "bottom" },
   { map = "6,-21", path = "bottom" },
   { map = "7,-21", path = "bottom" },
   { map = "6,-20", path = "bottom" },
   { map = "7,-20", path = "left" },
   { map = "6,-19", path = "bottom" },
   { map = "6,-18", path = "bottom" },
   { map = "6,-17", path = "bottom" },
   { map = "7,-18", path = "bottom" },
   { map = "7,-17", path = "bottom" },
   { map = "4,-22", path = "bottom" },
   { map = "3,-22", path = "bottom" },
   { map = "2,-22", path = "bottom" },
   { map = "0,-22", path = "bottom" },
   { map = "-1,-21", path = "bottom" },
   { map = "0,-21", path = "bottom" },
   { map = "1,-21", path = "bottom" },
   { map = "2,-21", path = "bottom" },
   { map = "3,-21", path = "bottom" },
   { map = "4,-21", path = "bottom" },
   { map = "4,-20", path = "bottom" },
   { map = "3,-20", path = "bottom" },
   { map = "2,-20", path = "bottom" },
   { map = "1,-20", path = "bottom" },
   { map = "0,-20", path = "bottom" },
   { map = "-1,-20", path = "bottom" },
   { map = "-1,-15", path = "right" },
   { map = "0,-15", path = "right" },
   { map = "-1,-16", path = "right" },
   { map = "0,-16", path = "right" },
   { map = "1,-16", path = "right" },
   { map = "2,-16", path = "right" },
   { map = "3,-16", path = "right" },
   { map = "-1,-17", path = "right" },
   { map = "0,-17", path = "right" },
   { map = "1,-17", path = "right" },
   { map = "2,-17", path = "right" },
   { map = "3,-17", path = "right" },
   { map = "-1,-19", path = "right" },
   { map = "0,-19", path = "right" },
   { map = "1,-19", path = "right" },
   { map = "2,-19", path = "right" },
   { map = "3,-19", path = "right" },
   { map = "3,-18", path = "right" },
   { map = "2,-18", path = "right" },
   { map = "1,-18", path = "right" },
   { map = "0,-18", path = "right" },
   { map = "-1,-18", path = "bottom" },
   { map = "-1,-14", path = "top" },
   { map = "0,-14", path = "top" },
   { map = "1,-14", path = "top" },
   { map = "2,-14", path = "top" },
   { map = "3,-15", path = "top" },
   { map = "2,-15", path = "top" },
   { map = "1,-15", path = "top" },
   { map = "5,-15", path = "top" },
   { map = "6,-15", path = "top" },
   { map = "7,-15", path = "top" },
   { map = "7,-16", path = "left" },
   { map = "6,-16", path = "left" },
   { map = "5,-16", path = "left" },
   { map = "4,-19", path = "bottom" },
   { map = "4,-18", path = "bottom" },
   { map = "4,-17", path = "bottom" },



   { map = "0,-22", path = "bottom", fight = true },
   { map = "1,-22", path = "bottom", fight = true },
   { map = "2,-22", path = "bottom", fight = true },
   { map = "3,-22", path = "bottom", fight = true },
   { map = "4,-22", path = "bottom", fight = true },
   { map = "5,-22", path = "bottom", fight = true },
   { map = "7,-21", path = "left", fight = true },
   { map = "7,-20", path = "left", fight = true },
   { map = "7,-19", path = "left", fight = true },
   { map = "7,-18", path = "left", fight = true },
   { map = "7,-17", path = "left", fight = true },
   { map = "7,-16", path = "left", fight = true },
   { map = "7,-15", path = "left", fight = true },
   { map = "6,-15", path = "top", fight = true },
   { map = "4,-15", path = "top", fight = true },
   { map = "5,-15", path = "top", fight = true },
   { map = "3,-14", path = "top", fight = true },
   { map = "2,-14", path = "top", fight = true },
   { map = "1,-14", path = "top", fight = true },
   { map = "0,-14", path = "top", fight = true },
   { map = "-1,-14", path = "top", fight = true },
   { map = "-1,-15", path = "right", fight = true },
   { map = "-1,-16", path = "right", fight = true },
   { map = "-1,-17", path = "right", fight = true },
   { map = "-1,-18", path = "right", fight = true },
   { map = "-1,-19", path = "right", fight = true },
   { map = "-1,-20", path = "right", fight = true },
   { map = "-1,-21", path = "right", fight = true },
   { map = "6,-21", path = "left|bottom", fight = true },
   { map = "0,-21", path = "top|left|right|bottom", fight = true },
   { map = "0,-20", path = "top|left|right|bottom", fight = true },
   { map = "0,-19", path = "top|left|right|bottom", fight = true },
   { map = "0,-18", path = "top|left|right|bottom", fight = true },
   { map = "0,-17", path = "top|left|right|bottom", fight = true },
   { map = "0,-16", path = "top|left|right|bottom", fight = true },
   { map = "0,-15", path = "top|left|right|bottom", fight = true },
   { map = "1,-15", path = "top|left|right|bottom", fight = true },
   { map = "1,-16", path = "top|left|right|bottom", fight = true },
   { map = "1,-17", path = "left|right|bottom", fight = true },
   { map = "2,-15", path = "top|left|right|bottom", fight = true },
   { map = "3,-15", path = "top|left|right|bottom", fight = true },
   { map = "3,-16", path = "top|left|right|bottom", fight = true },
   { map = "2,-16", path = "top|left|right|bottom", fight = true },
   { map = "2,-17", path = "top|left|right|bottom", fight = true },
   { map = "3,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-16", path = "top|left|right|bottom", fight = true },
   { map = "5,-16", path = "top|left|right|bottom", fight = true },
   { map = "5,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-18", path = "top|left|right|bottom", fight = true },
   { map = "5,-18", path = "top|left|right|bottom", fight = true },
   { map = "4,-18", path = "top|left|right|bottom", fight = true },
   { map = "4,-17", path = "top|left|right|bottom", fight = true },
   { map = "3,-18", path = "top|left|right|bottom", fight = true },
   { map = "6,-19", path = "top|left|right|bottom", fight = true },
   { map = "6,-20", path = "top|left|right|bottom", fight = true },
   { map = "5,-20", path = "top|left|right|bottom", fight = true },
   { map = "5,-19", path = "top|left|right|bottom", fight = true },
   { map = "5,-21", path = "top|left|right|bottom", fight = true },
   { map = "4,-21", path = "top|left|right|bottom", fight = true },
   { map = "2,-21", path = "top|left|right|bottom", fight = true },
   { map = "3,-21", path = "top|left|right|bottom", fight = true },
   { map = "1,-21", path = "top|left|right|bottom", fight = true },
   { map = "1,-20", path = "top|left|right|bottom", fight = true },
   { map = "1,-19", path = "top|left|right|bottom", fight = true },
   { map = "2,-19", path = "top|left|right|bottom", fight = true },
   { map = "3,-19", path = "top|left|right|bottom", fight = true },
   { map = "4,-19", path = "top|left|right|bottom", fight = true },
   { map = "4,-20", path = "top|left|right|bottom", fight = true },
   { map = "3,-20", path = "top|left|right|bottom", fight = true },
   { map = "2,-20", path = "top|left|right|bottom", fight = true },
   { map = "1,-18", path = "top|left|right", fight = true },
   { map = "2,-18", path = "top|left|right", fight = true },
    {map="4,-16" ,path="right"},

  }
end



function piou2()
  MIN_MONSTERS = 1
  MAX_MONSTERS = 4
  AUTO_DELETE = {} --
  return {
  	
   { map = "0,-22", path = "bottom", fight = true },
   { map = "1,-22", path = "bottom", fight = true },
   { map = "2,-22", path = "bottom", fight = true },
   { map = "3,-22", path = "bottom", fight = true },
   { map = "4,-22", path = "bottom", fight = true },
   { map = "5,-22", path = "bottom", fight = true },
   { map = "7,-21", path = "left", fight = true },
   { map = "7,-20", path = "left", fight = true },
   { map = "7,-19", path = "left", fight = true },
   { map = "7,-18", path = "left", fight = true },
   { map = "7,-17", path = "left", fight = true },
   { map = "7,-16", path = "left", fight = true },
   { map = "7,-15", path = "left", fight = true },
   { map = "6,-15", path = "top", fight = true },
   { map = "4,-15", path = "top", fight = true },
   { map = "5,-15", path = "top", fight = true },
   { map = "3,-14", path = "top", fight = true },
   { map = "2,-14", path = "top", fight = true },
   { map = "1,-14", path = "top", fight = true },
   { map = "0,-14", path = "top", fight = true },
   { map = "-1,-14", path = "top", fight = true },
   { map = "-1,-15", path = "right", fight = true },
   { map = "-1,-16", path = "right", fight = true },
   { map = "-1,-17", path = "right", fight = true },
   { map = "-1,-18", path = "right", fight = true },
   { map = "-1,-19", path = "right", fight = true },
   { map = "-1,-20", path = "right", fight = true },
   { map = "-1,-21", path = "right", fight = true },
   { map = "6,-21", path = "left|bottom", fight = true },
   { map = "0,-21", path = "top|left|right|bottom", fight = true },
   { map = "0,-20", path = "top|left|right|bottom", fight = true },
   { map = "0,-19", path = "top|left|right|bottom", fight = true },
   { map = "0,-18", path = "top|left|right|bottom", fight = true },
   { map = "0,-17", path = "top|left|right|bottom", fight = true },
   { map = "0,-16", path = "top|left|right|bottom", fight = true },
   { map = "0,-15", path = "top|left|right|bottom", fight = true },
   { map = "1,-15", path = "top|left|right|bottom", fight = true },
   { map = "1,-16", path = "top|left|right|bottom", fight = true },
   { map = "1,-17", path = "left|right|bottom", fight = true },
   { map = "2,-15", path = "top|left|right|bottom", fight = true },
   { map = "3,-15", path = "top|left|right|bottom", fight = true },
   { map = "3,-16", path = "top|left|right|bottom", fight = true },
   { map = "2,-16", path = "top|left|right|bottom", fight = true },
   { map = "2,-17", path = "top|left|right|bottom", fight = true },
   { map = "3,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-16", path = "top|left|right|bottom", fight = true },
   { map = "5,-16", path = "top|left|right|bottom", fight = true },
   { map = "5,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-18", path = "top|left|right|bottom", fight = true },
   { map = "5,-18", path = "top|left|right|bottom", fight = true },
   { map = "4,-18", path = "top|left|right|bottom", fight = true },
   { map = "4,-17", path = "top|left|right|bottom", fight = true },
   { map = "3,-18", path = "top|left|right|bottom", fight = true },
   { map = "6,-19", path = "top|left|right|bottom", fight = true },
   { map = "6,-20", path = "top|left|right|bottom", fight = true },
   { map = "5,-20", path = "top|left|right|bottom", fight = true },
   { map = "5,-19", path = "top|left|right|bottom", fight = true },
   { map = "5,-21", path = "top|left|right|bottom", fight = true },
   { map = "4,-21", path = "top|left|right|bottom", fight = true },
   { map = "2,-21", path = "top|left|right|bottom", fight = true },
   { map = "3,-21", path = "top|left|right|bottom", fight = true },
   { map = "1,-21", path = "top|left|right|bottom", fight = true },
   { map = "1,-20", path = "top|left|right|bottom", fight = true },
   { map = "1,-19", path = "top|left|right|bottom", fight = true },
   { map = "2,-19", path = "top|left|right|bottom", fight = true },
   { map = "3,-19", path = "top|left|right|bottom", fight = true },
   { map = "4,-19", path = "top|left|right|bottom", fight = true },
   { map = "4,-20", path = "top|left|right|bottom", fight = true },
   { map = "3,-20", path = "top|left|right|bottom", fight = true },
   { map = "2,-20", path = "top|left|right|bottom", fight = true },
   { map = "1,-18", path = "top|left|right", fight = true },
   { map = "2,-18", path = "top|left|right", fight = true },
    {map="4,-16" ,path="right"},
  }
end


function piou3()
    MIN_MONSTERS = 2
  MAX_MONSTERS = 8
  AUTO_DELETE = {} --
  return {
   { map = "0,-22", path = "bottom", fight = true },
   { map = "1,-22", path = "bottom", fight = true },
   { map = "2,-22", path = "bottom", fight = true },
   { map = "3,-22", path = "bottom", fight = true },
   { map = "4,-22", path = "bottom", fight = true },
   { map = "5,-22", path = "bottom", fight = true },
   { map = "7,-21", path = "left", fight = true },
   { map = "7,-20", path = "left", fight = true },
   { map = "7,-19", path = "left", fight = true },
   { map = "7,-18", path = "left", fight = true },
   { map = "7,-17", path = "left", fight = true },
   { map = "7,-16", path = "left", fight = true },
   { map = "7,-15", path = "left", fight = true },
   { map = "6,-15", path = "top", fight = true },
   { map = "4,-15", path = "top", fight = true },
   { map = "5,-15", path = "top", fight = true },
   { map = "3,-14", path = "top", fight = true },
   { map = "2,-14", path = "top", fight = true },
   { map = "1,-14", path = "top", fight = true },
   { map = "0,-14", path = "top", fight = true },
   { map = "-1,-14", path = "top", fight = true },
   { map = "-1,-15", path = "right", fight = true },
   { map = "-1,-16", path = "right", fight = true },
   { map = "-1,-17", path = "right", fight = true },
   { map = "-1,-18", path = "right", fight = true },
   { map = "-1,-19", path = "right", fight = true },
   { map = "-1,-20", path = "right", fight = true },
   { map = "-1,-21", path = "right", fight = true },
   { map = "6,-21", path = "left|bottom", fight = true },
   { map = "0,-21", path = "top|left|right|bottom", fight = true },
   { map = "0,-20", path = "top|left|right|bottom", fight = true },
   { map = "0,-19", path = "top|left|right|bottom", fight = true },
   { map = "0,-18", path = "top|left|right|bottom", fight = true },
   { map = "0,-17", path = "top|left|right|bottom", fight = true },
   { map = "0,-16", path = "top|left|right|bottom", fight = true },
   { map = "0,-15", path = "top|left|right|bottom", fight = true },
   { map = "1,-15", path = "top|left|right|bottom", fight = true },
   { map = "1,-16", path = "top|left|right|bottom", fight = true },
   { map = "1,-17", path = "left|right|bottom", fight = true },
   { map = "2,-15", path = "top|left|right|bottom", fight = true },
   { map = "3,-15", path = "top|left|right|bottom", fight = true },
   { map = "3,-16", path = "top|left|right|bottom", fight = true },
   { map = "2,-16", path = "top|left|right|bottom", fight = true },
   { map = "2,-17", path = "top|left|right|bottom", fight = true },
   { map = "3,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-16", path = "top|left|right|bottom", fight = true },
   { map = "5,-16", path = "top|left|right|bottom", fight = true },
   { map = "5,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-17", path = "top|left|right|bottom", fight = true },
   { map = "6,-18", path = "top|left|right|bottom", fight = true },
   { map = "5,-18", path = "top|left|right|bottom", fight = true },
   { map = "4,-18", path = "top|left|right|bottom", fight = true },
   { map = "4,-17", path = "top|left|right|bottom", fight = true },
   { map = "3,-18", path = "top|left|right|bottom", fight = true },
   { map = "6,-19", path = "top|left|right|bottom", fight = true },
   { map = "6,-20", path = "top|left|right|bottom", fight = true },
   { map = "5,-20", path = "top|left|right|bottom", fight = true },
   { map = "5,-19", path = "top|left|right|bottom", fight = true },
   { map = "5,-21", path = "top|left|right|bottom", fight = true },
   { map = "4,-21", path = "top|left|right|bottom", fight = true },
   { map = "2,-21", path = "top|left|right|bottom", fight = true },
   { map = "3,-21", path = "top|left|right|bottom", fight = true },
   { map = "1,-21", path = "top|left|right|bottom", fight = true },
   { map = "1,-20", path = "top|left|right|bottom", fight = true },
   { map = "1,-19", path = "top|left|right|bottom", fight = true },
   { map = "2,-19", path = "top|left|right|bottom", fight = true },
   { map = "3,-19", path = "top|left|right|bottom", fight = true },
   { map = "4,-19", path = "top|left|right|bottom", fight = true },
   { map = "4,-20", path = "top|left|right|bottom", fight = true },
   { map = "3,-20", path = "top|left|right|bottom", fight = true },
   { map = "2,-20", path = "top|left|right|bottom", fight = true },
   { map = "1,-18", path = "top|left|right", fight = true },
   { map = "2,-18", path = "top|left|right", fight = true },
   {map="4,-16" ,path="right"},
 }
end


function boo()
MIN_MONSTERS = 2
MAX_MONSTERS = 8
AUTO_DELETE = {} 
  return {

   { map = "-2,-20", path = "right" },
   { map = "8,-19", path = "left" },
   { map = "7,-19", path = "left" },
   { map = "5,-23", path = "bottom" },
   { map = "5,-22", path = "bottom" },
   { map = "4,-14", path = "top" },
   { map = "4,-15", path = "top" },
   { map = "-2,-24", path = "bottom" },
   { map = "-2,-23", path = "bottom" },
   { map = "-2,-22", path = "bottom" },
   { map = "-2,-21", path = "bottom" },
   { map = "5,-24", path = "bottom" },
   { map = "5,-25", path = "bottom" },
   { map = "5,-26", path = "bottom" },
   { map = "5,-27", path = "bottom" },
   { map = "4,-27", path = "bottom" },
   { map = "3,-27", path = "bottom" },
   { map = "2,-27", path = "bottom" },
   { map = "1,-27", path = "bottom" },
   { map = "0,-27", path = "bottom" },
   { map = "0,-26", path = "bottom" },
   { map = "-1,-26", path = "bottom" },
   { map = "-1,-27", path = "bottom" },
   { map = "-2,-27", path = "bottom" },
   { map = "-2,-26", path = "bottom" },
   { map = "-2,-25", path = "bottom" },
   { map = "-1,-25", path = "bottom" },
   { map = "0,-25", path = "bottom" },
   { map = "1,-25", path = "bottom" },
   { map = "1,-26", path = "bottom" },
   { map = "2,-26", path = "bottom" },
   { map = "2,-25", path = "bottom" },
   { map = "3,-25", path = "bottom" },
   { map = "3,-26", path = "bottom" },
   { map = "4,-26", path = "bottom" },
   { map = "4,-25", path = "bottom" },
   { map = "4,-24", path = "bottom" },
   { map = "3,-24", path = "bottom" },
   { map = "2,-24", path = "bottom" },
   { map = "1,-24", path = "bottom" },
   { map = "0,-24", path = "bottom" },
   { map = "-1,-24", path = "bottom" },
   { map = "2,-23", path = "left" },
   { map = "0,-23", path = "left" },
   { map = "1,-23", path = "left" },
   { map = "-1,-23", path = "left" },
   { map = "-1,-22", path = "left" },
   { map = "3,-23", path = "right" },
   { map = "4,-23", path = "right" },
   { map = "8,-23", path = "left" },
   { map = "6,-23", path = "left" },
   { map = "7,-23", path = "left" },
   { map = "8,-24", path = "left" },
   { map = "8,-25", path = "left" },
   { map = "7,-25", path = "left" },
   { map = "7,-26", path = "left" },
   { map = "7,-27", path = "left" },
   { map = "6,-27", path = "left" },
   { map = "6,-25", path = "left" },
   { map = "6,-26", path = "left" },
   { map = "6,-24", path = "left" },
   { map = "7,-24", path = "left" },
   { map = "11,-19", path = "left" },
   { map = "11,-20", path = "left" },
   { map = "11,-21", path = "left" },
   { map = "11,-22", path = "left" },
   { map = "10,-22", path = "left" },
   { map = "9,-22", path = "left" },
   { map = "8,-22", path = "left" },
   { map = "10,-21", path = "left" },
   { map = "9,-21", path = "left" },
   { map = "10,-20", path = "left" },
   { map = "9,-20", path = "left" },
   { map = "10,-19", path = "left" },
   { map = "9,-19", path = "left" },
   { map = "11,-17", path = "left" },
   { map = "11,-18", path = "left" },
   { map = "11,-16", path = "left" },
   { map = "11,-15", path = "left" },
   { map = "12,-15", path = "left" },
   { map = "13,-15", path = "left" },
   { map = "12,-16", path = "left" },
   { map = "12,-17", path = "left" },
   { map = "12,-18", path = "left" },
   { map = "12,-19", path = "left" },
   { map = "12,-20", path = "left" },
   { map = "12,-21", path = "left" },
   { map = "12,-22", path = "left" },
   { map = "10,-15", path = "left" },
   { map = "9,-15", path = "left" },
   { map = "10,-16", path = "left" },
   { map = "9,-16", path = "left" },
   { map = "10,-17", path = "left" },
   { map = "9,-17", path = "left" },
   { map = "10,-18", path = "left" },
   { map = "9,-18", path = "left" },
   { map = "8,-15", path = "top" },
   { map = "8,-16", path = "top" },
   { map = "8,-17", path = "top" },
   { map = "8,-18", path = "top" },
   { map = "8,-21", path = "bottom" },
   { map = "8,-20", path = "bottom" },
   { map = "7,-22", path = "top" },
   { map = "6,-22", path = "top" },
   { map = "7,-9", path = "top" },
   { map = "6,-9", path = "top" },
   { map = "5,-9", path = "top" },
   { map = "4,-9", path = "top" },
   { map = "3,-9", path = "top" },
   { map = "2,-9", path = "top" },
   { map = "2,-10", path = "top" },
   { map = "2,-11", path = "top" },
   { map = "2,-12", path = "top" },
   { map = "3,-12", path = "top" },
   { map = "4,-12", path = "top" },
   { map = "5,-12", path = "top" },
   { map = "6,-12", path = "top" },
   { map = "7,-12", path = "top" },
   { map = "8,-12", path = "top" },
   { map = "9,-12", path = "top" },
   { map = "10,-12", path = "top" },
   { map = "11,-12", path = "top" },
   { map = "11,-13", path = "top" },
   { map = "11,-14", path = "top" },
   { map = "10,-13", path = "top" },
   { map = "10,-14", path = "top" },
   { map = "9,-13", path = "left" },
   { map = "9,-14", path = "left" },
   { map = "8,-14", path = "left" },
   { map = "7,-14", path = "left" },
   { map = "6,-14", path = "left" },
   { map = "5,-14", path = "left" },
   { map = "8,-13", path = "left" },
   { map = "7,-13", path = "left" },
   { map = "6,-13", path = "left" },
   { map = "5,-13", path = "left" },
   { map = "9,-11", path = "left" },
   { map = "10,-11", path = "left" },
   { map = "11,-11", path = "left" },
   { map = "10,-10", path = "left" },
   { map = "9,-10", path = "left" },
   { map = "9,-9", path = "left" },
   { map = "8,-9", path = "left" },
   { map = "8,-10", path = "left" },
   { map = "8,-11", path = "left" },
   { map = "7,-11", path = "left" },
   { map = "7,-10", path = "left" },
   { map = "6,-10", path = "left" },
   { map = "6,-11", path = "left" },
   { map = "5,-11", path = "left" },
   { map = "5,-10", path = "left" },
   { map = "4,-10", path = "top" },
   { map = "4,-11", path = "top" },
   { map = "4,-13", path = "top" },
   { map = "3,-10", path = "right" },
   { map = "3,-11", path = "right" },
   { map = "3,-13", path = "right" },
   { map = "2,-13", path = "right" },
   { map = "1,-13", path = "right" },
   { map = "0,-13", path = "right" },
   { map = "-1,-13", path = "right" },
   { map = "-2,-13", path = "right" },
   { map = "-2,-12", path = "right" },
   { map = "-1,-12", path = "right" },
   { map = "0,-12", path = "right" },
   { map = "1,-12", path = "right" },
   { map = "1,-11", path = "right" },
   { map = "-1,-11", path = "right" },
   { map = "-2,-11", path = "right" },
   { map = "0,-11", path = "right" },
   { map = "1,-10", path = "right" },
   { map = "0,-10", path = "right" },
   { map = "-1,-10", path = "right" },
   { map = "-2,-10", path = "right" },
   { map = "1,-9", path = "right" },
   { map = "-4,-14", path = "right" },
   { map = "-3,-14", path = "right" },
   { map = "-2,-14", path = "right" },
   { map = "-3,-13", path = "right" },
   { map = "-4,-13", path = "right" },
   { map = "-4,-15", path = "right" },
   { map = "-4,-16", path = "right" },
   { map = "-4,-17", path = "right" },
   { map = "-4,-18", path = "right" },
   { map = "-4,-20", path = "right" },
   { map = "-4,-19", path = "right" },
   { map = "-4,-21", path = "right" },
   { map = "-5,-23", path = "right" },
   { map = "-4,-22", path = "right" },
   { map = "-4,-23", path = "right" },
   { map = "-3,-23", path = "right" },
   { map = "-3,-22", path = "right" },
   { map = "-3,-21", path = "right" },
   { map = "-2,-18", path = "top" },
   { map = "-3,-19", path = "top" },
   { map = "-2,-19", path = "top" },
   { map = "-3,-18", path = "top" },
   { map = "-3,-20", path = "right" },
   { map = "-2,-17", path = "bottom" },
   { map = "-2,-16", path = "bottom" },
   { map = "-2,-15", path = "bottom" },
   { map = "-3,-15", path = "bottom" },
   { map = "-3,-16", path = "bottom" },
   { map = "-3,-17", path = "bottom" },
   { map = "5,-21", path = "bottom" },
   { map = "5,-20", path = "bottom" },
   { map = "5,-19", path = "bottom" },
   { map = "5,-18", path = "bottom" },
   { map = "5,-17", path = "bottom" },
   { map = "6,-21", path = "bottom" },
   { map = "7,-21", path = "bottom" },
   { map = "6,-20", path = "bottom" },
   { map = "7,-20", path = "left" },
   { map = "6,-19", path = "bottom" },
   { map = "6,-18", path = "bottom" },
   { map = "6,-17", path = "bottom" },
   { map = "7,-18", path = "bottom" },
   { map = "7,-17", path = "bottom" },
   { map = "4,-22", path = "bottom" },
   { map = "3,-22", path = "bottom" },
   { map = "2,-22", path = "bottom" },
   { map = "0,-22", path = "bottom" },
   { map = "-1,-21", path = "bottom" },
   { map = "0,-21", path = "bottom" },
   { map = "1,-21", path = "bottom" },
   { map = "2,-21", path = "bottom" },
   { map = "3,-21", path = "bottom" },
   { map = "4,-21", path = "bottom" },
   { map = "4,-20", path = "bottom" },
   { map = "3,-20", path = "bottom" },
   { map = "2,-20", path = "bottom" },
   { map = "1,-20", path = "bottom" },
   { map = "0,-20", path = "bottom" },
   { map = "-1,-20", path = "bottom" },
   { map = "-1,-15", path = "right" },
   { map = "0,-15", path = "right" },
   { map = "-1,-16", path = "right" },
   { map = "0,-16", path = "right" },
   { map = "1,-16", path = "right" },
   { map = "2,-16", path = "right" },
   { map = "3,-16", path = "right" },
   { map = "-1,-17", path = "right" },
   { map = "0,-17", path = "right" },
   { map = "1,-17", path = "right" },
   { map = "2,-17", path = "right" },
   { map = "3,-17", path = "right" },
   { map = "-1,-19", path = "right" },
   { map = "0,-19", path = "right" },
   { map = "1,-19", path = "right" },
   { map = "2,-19", path = "right" },
   { map = "3,-19", path = "right" },
   { map = "3,-18", path = "right" },
   { map = "2,-18", path = "right" },
   { map = "1,-18", path = "right" },
   { map = "0,-18", path = "right" },
   { map = "-1,-18", path = "bottom" },
   { map = "-1,-14", path = "top" },
   { map = "0,-14", path = "top" },
   { map = "1,-14", path = "top" },
   { map = "2,-14", path = "top" },
   { map = "3,-15", path = "top" },
   { map = "2,-15", path = "top" },
   { map = "1,-15", path = "top" },
   { map = "5,-15", path = "top" },
   { map = "6,-15", path = "top" },
   { map = "7,-15", path = "top" },
   { map = "7,-16", path = "left" },
   { map = "6,-16", path = "left" },
   { map = "5,-16", path = "left" },
   { map = "4,-19", path = "bottom" },
   { map = "4,-18", path = "bottom" },
   { map = "4,-17", path = "bottom" },

   {map = "4,-19", path = "bottom"},
    {map = "4,-18", path = "bottom"},
    {map = "4,-17", path = "bottom"},
    {map = "4,-16", path = "bottom"},
    {map = "4,-15", path = "bottom(555)"},
    {map = "4,-14", path = "bottom"},
    {map = "4,-13", path = "bottom"},
    {map = "4,-12", path = "bottom"},
    {map = "4,-11", path = "bottom"},
    {map = "4,-10", path = "bottom"},
    {map = "4,-9", path = "bottom"},
    {map = "4,-8", path = "bottom"},
    {map = "4,-7", path = "bottom"},
    {map = "4,-6", path = "bottom"},
    {map = "4,-5", path = "bottom"},
    {map = "4,-4", path = "bottom"},
    {map = "4,-3", path = "bottom"},
    {map = "4,-2", path = "bottom"},
    {map = "4,-1", path = "bottom"},
    {map = "4,0", path = "bottom"},
    {map = "4,1", path = "bottom"},
    {map = "4,2", path = "bottom"},
    {map = "4,3", path = "bottom"},
    {map = "4,4", path = "bottom"},
    {map = "4,5", path = "bottom"},
    {map = "4,6", path = "bottom"},
    {map = "4,7", path = "right"},
    {map = "5,7", path = "zaap(-2)" ,path="right"},

    {map = "6,7",custom=equip2, path = "right"},
    {map = "7,7", path = "right"},
    {map = "8,7",path = "right"},
    {map = "9,7", path = "right"},
    {map = "10,7", path = "right"},
    {map = "11,7", path = "right"},
    {map = "12,7", path = "top", fight = true},
    {map = "12,6", path = "top", fight = true},
    {map = "13,6", path = "bottom", fight = true},
    {map = "12,5", path = "right"},
    {map = "13,5", path = "bottom", fight = true},
    {map = "13,7", path = "bottom", fight = true},
    {map = "13,8", path = "left", fight = true},
    {map = "12,8", path = "top", fight = true},
    {map = "2,-2", path = "bottom"},
    {map = "2,-1", path = "bottom"},
    {map = "2,0", path = "right"},
    {map = "4,0", path = "right"},
    {map = "5,0", path = "bottom"},
    {map = "5,1", path = "bottom"},
    {map = "5,2", path = "bottom"},
    {map = "5,3", path = "bottom"},
    {map = "5,4", path = "bottom"},
    {map = "5,5", path = "right"},
    {map = "6,5", path = "right"},
    {map = "7,5", path = "bottom"},
    {map = "7,6", path = "bottom"},
    {map = "3,0", path = "right"},



  }
end

function frigost()
  return{

   { map = "13,4", path = "left" },
   { map = "13,5", path = "left" },
   { map = "13,6", path = "left" },
   { map = "13,7", path = "left" },
   { map = "13,8", path = "left" },
   { map = "12,8", path = "left" },
   { map = "12,7", path = "left" },
   { map = "12,6", path = "left" },
   { map = "12,5", path = "left" },
   { map = "12,4", path = "left" },
   { map = "11,4", path = "left" },
   { map = "11,5", path = "left" },
   { map = "11,6", path = "left" },
   { map = "11,7", path = "left" },
   { map = "11,8", path = "left" },
   { map = "10,8", path = "left" },
   { map = "9,8", path = "left" },
   { map = "9,7", path = "left" },
   { map = "9,6", path = "left" },
   { map = "10,6", path = "left" },
   { map = "10,5", path = "left" },
   { map = "10,4", path = "left" },
   { map = "9,4", path = "left" },
   { map = "9,5", path = "left" },
   { map = "8,5", path = "left" },
   { map = "7,5", path = "left" },
   { map = "7,6", path = "left" },
   { map = "7,8", path = "left" },
   { map = "8,8", path = "left" },
   { map = "8,7", path = "left" },
   { map = "7,7", path = "left" },
   { map = "8,6", path = "left" },
   { map = "7,4", path = "left" },
   { map = "8,4", path = "left" },
   { map = "6,4", path = "left" },
   { map = "6,5", path = "left" },
   { map = "6,6", path = "left" },
   { map = "6,7", path = "left" },
   { map = "6,8", path = "left" },
   { map = "5,8", path = "left" },
   { map = "5,7", path = "left" },
   { map = "5,6", path = "left" },
   { map = "5,5", path = "left" },
   { map = "5,4", path = "left" },
   { map = "4,4", path = "left" },
   { map = "4,5", path = "left" },
   { map = "4,6", path = "left" },
   { map = "4,7", path = "left" },
   { map = "4,8", path = "left" },
   { map = "3,8", path = "top" },
   { map = "3,7", path = "top" },
   { map = "3,6", path = "top" },
   { map = "3,2", path = "top" },
   { map = "3,5", path = "top" },
   { map = "3,4", path = "top" },
   { map = "3,3", path = "top" },
   { map = "3,1", path = "top" },
   { map = "3,0", path = "top" },
   { map = "3,-1", path = "top" },
   { map = "3,-2", path = "top" },
   { map = "3,-3", path = "right" },
   { map = "4,-3", path = "top" },
   { map = "4,-4", path = "top" },
   { map = "4,-5", path = "top" },
   { map = "4,-6", path = "top" },
   { map = "4,-7", path = "top" },
   { map = "4,-8", path = "left" },
   { map = "4,-9", path = "top" },
   { map = "4,-10", path = "top" },
   { map = "4,-11", path = "top" },
   { map = "4,-12", path = "top" },
   { map = "4,-13", path = "top" },
   { map = "4,-14", path = "top" },
   { map = "4,-15", path = "top" },
   { map = "4,-16", path = "top" },
   { map = "4,-17", path = "top" },
   { map = "4,-18", path = "top" },


    {map = "4,-19", path = "top"},
    {map = "4,-20", path = "left"},
    {map = "3,-20", path = "left"},
    {map = "2,-20", path = "left"},
    {map = "1,-20", path = "left"},
    {map = "0,-20", path = "left"},
    {map = "-1,-20", path = "left"},
    {map = "-2,-20", path = "left"},
    {map = "-3,-20", path = "left"},
    {map = "-4,-20", path = "left"},
    {map = "-5,-20", path = "left"},
    {map = "-6,-20", path = "left"},
    {map = "-7,-20", path = "left"},
    {map = "-8,-20", path = "left"},
    {map = "-9,-20", path = "left"},
    {map = "-10,-20", path = "left"},
    {map = "-11,-20", path = "left"},
    {map = "-12,-20", path = "left"},
    {map = "-13,-20", path = "left"},
    {map = "-14,-20", path = "left"},
    {map = "-15,-20", path = "left"},
    {map = "-16,-20", path = "left"},
    {map = "-17,-20", path = "left"},
    {map = "-18,-20", path = "left"},
    {map = "-19,-20", path = "left"},
        {map = "-20,-20", path = "bottom"},
    {map = "-20,-19", path = "bottom"},
    {map = "-20,-17", path = "bottom"},
    {map = "-20,-18", path = "bottom"},
    {map = "-20,-16", path = "bottom"},
    {map = "-20,-15", path = "bottom"},
    {map = "-20,-14", path = "left"},
    {map = "-21,-14", path = "left"},
    {map = "-22,-14", path = "left"},
    {map = "-23,-14", path = "left"},
    {map = "-24,-14", path = "left"},
    {map = "-25,-14", path = "left"},
    {map = "-26,-14", path = "left"},
    {map = "-27,-14", path = "left"},
    {map = "-28,-14", path = "bottom"},
    {map = "-28,-13", path = "bottom"},
    {map = "-28,-12", path = "left"},
    {map = "-29,-12", path = "left"},
    {map = "-30,-12", path = "left"},
    {map = "-31,-12", path = "bottom"},
    {map = "-31,-11", path = "left"},
    {map = "-32,-11", path = "left"},
    {map = "-33,-11", path = "top"},
    {map = "-33,-12", path = "top"},
    {map = "-33,-13", path = "top"},
    {map = "-33,-14", path = "top"},
    {map = "-33,-15", path = "left(112)"},
    {map = "148752", custom = frifri },
        {map = "56623104", custom = frifri },
        {map = "56624128", custom = frifri },
        {map = "56625152", custom = frifri },
        {map = "54175012", custom = fri, path = "right(55)" },
        {map = "-80,-38", path = "top(7)"},
        {map = "-80,-39", path = "right"},
    {map = "-79,-39", custom=equip3, path = "right"},
    {map = "-78,-39", path = "top"},
    {map = "-78,-40", path = "top"},

{ map = "-76,-47", fight = false, path = "bottom" },
{ map = "-86,-44", fight = false, path = "right" },
{ map = "-72,-34", fight = false, path = "left" },
{ map = "-73,-33", fight = false, path = "top" },
{ map = "-83,-46", fight = true, path = "right"},
{ map = "-82,-46", fight = true, path = "right"},
{ map = "-81,-46", fight = true, path = "right"},
{ map = "-80,-46", fight = true, path = "right"},
{ map = "-79,-46", fight = true, path = "right"},
{ map = "-78,-46", fight = true, path = "right"},
{ map = "-77,-46", fight = true, path = "bottom" },
{ map = "-76,-46", fight = true, path = "bottom", },
{ map = "-84,-45", fight = true, path = "right"},
{ map = "-83,-45", fight = true, path = "top"},
{ map = "-82,-45", fight = true, path = "left|bottom"},
{ map = "-81,-45", fight = true, path = "left"},
{ map = "-80,-45", fight = true, path = "top|left|right"},
{ map = "-79,-45", fight = true, path = "right"},
{ map = "-78,-45", fight = true, path = "top|right"},
{ map = "-77,-45", fight = true, path = "right|bottom" },
{ map = "-76,-45", fight = true, path = "right", },
{ map = "-75,-45", fight = true, path = "bottom", },
{ map = "-85,-44", fight = true, path = "right"},
{ map = "-84,-44", fight = true, path = "top"},
{ map = "-83,-44", fight = true, path = "bottom"},
{ map = "-82,-44", fight = true, path = "left|right"},
{ map = "-81,-44", fight = true, path = "bottom"},
{ map = "-80,-44", fight = true, path = "top"},
{ map = "-79,-44", fight = true, path = "top"},
{ map = "-78,-44", fight = true, path = "bottom"},
{ map = "-77,-44", fight = true, path = "left" },
{ map = "-76,-44", fight = true, path = "top", },
{ map = "-75,-44", fight = true, path = "right", },
{ map = "-74,-44", fight = true, path = "bottom", },
{ map = "-85,-43", fight = true, path = "right"},
{ map = "-84,-43", fight = true, path = "top"},
{ map = "-83,-43", fight = true, path = "bottom"},
{ map = "-82,-43", fight = true, path = "bottom"},
{ map = "-81,-43", fight = true, path = "left"},
{ map = "-80,-43", fight = true, path = "top"},
{ map = "-79,-43", fight = true, path = "top"},
{ map = "-78,-43", fight = true, path = "right"},
{ map = "-77,-43", fight = true, path = "bottom" },
{ map = "-76,-43", fight = true, path = "top|right", },
{ map = "-75,-43", fight = true, path = "bottom", },
{ map = "-74,-43", fight = true, path = "right", },
{ map = "-73,-43", fight = true, path = "bottom", },
{ map = "-85,-42", fight = true, path = "top"},
{ map = "-84,-42", fight = true, path = "top|left"},
{ map = "-83,-42", fight = true, path = "left"},
{ map = "-82,-42", fight = true, path = "right"},
{ map = "-81,-42", fight = true, path = "bottom"},
{ map = "-80,-42", fight = true, path = "top"},
{ map = "-79,-42", fight = true, path = "top"},
{ map = "-78,-42", fight = true, path = "left"},
{ map = "-77,-42", fight = true, path = "right" },
{ map = "-76,-42", fight = true, path = "top", },
{ map = "-75,-42", fight = true, path = "right", },
{ map = "-74,-42", fight = true, path = "right", },
{ map = "-73,-42", fight = true, path = "bottom", },
{ map = "-85,-41", fight = true, path = "top"},
{ map = "-84,-41", fight = true, path = "left|bottom"},
{ map = "-83,-41", fight = true, path = "left"},
{ map = "-82,-41", fight = true, path = "left"},
{ map = "-81,-41", fight = true, path = "left"},
{ map = "-80,-41", fight = true, path = "top"},
{ map = "-79,-41", fight = true, path = "bottom"},
{ map = "-78,-41", path = "top|left|right|bottom" },
{ map = "-76,-41", fight = true, path = "right", },
{ map = "-75,-41", fight = true, path = "right", },
{ map = "-74,-41", fight = true, path = "right", },
{ map = "-73,-41", fight = true, path = "top|right", },
{ map = "-72,-41", fight = true, path = "bottom", },
{ map = "-84,-40", fight = true, path = "top", },
{ map = "-82,-40", fight = true, path = "top"},
{ map = "-81,-40", fight = true, path = "left"},
{ map = "-80,-40", fight = true, path = "top"},
{ map = "-79,-40", fight = true, path = "left"},
{ map = "-78,-40", fight = true, path = "bottom"},
{ map = "-77,-40", fight = true, path = "right", },
{ map = "-76,-40", fight = true, path = "right", },
{ map = "-75,-40", fight = true, path = "right", },
{ map = "-74,-40", fight = true, path = "right", },
{ map = "-73,-40", fight = true, path = "right|bottom", },
{ map = "-72,-40", fight = true, path = "bottom", },
{ map = "-81,-39", fight = true, path = "top"},
{ map = "-80,-39", fight = true, path = "left"},
{ map = "-79,-39", fight = true, path = "left"},
{ map = "-78,-39", fight = true, path = "left|right|bottom"},
{ map = "-77,-39", fight = true, path = "top", },
{ map = "-76,-39", fight = true, path = "bottom", },
{ map = "-75,-39", fight = true, path = "left", },
{ map = "-74,-39", fight = true, path = "left", },
{ map = "-73,-39", fight = true, path = "left|bottom", },
{ map = "-72,-39", fight = true, path = "bottom", },
{ map = "-80,-38", fight = true, path = "top"},
{ map = "-79,-38", fight = true, path = "left"},
{ map = "-78,-38", fight = true, path = "bottom"},
{ map = "-77,-38", fight = true, path = "left", },
{ map = "-76,-38", fight = true, path = "right|bottom", },
{ map = "-75,-38", fight = true, path = "right", },
{ map = "-74,-38", fight = true, path = "bottom", },
{ map = "-73,-38", fight = true, path = "bottom", },
{ map = "-72,-38", fight = true, path = "left", },
{ map = "-79,-37", fight = true, path = "top", },
{ map = "-78,-37", fight = true, path = "left", },
{ map = "-77,-37", fight = true, path = "top", },
{ map = "-76,-37", fight = true, path = "right|bottom", },
{ map = "-75,-37", fight = true, path = "right", },
{ map = "-74,-37", fight = true, path = "bottom", },
{ map = "-73,-37", fight = true, path = "bottom", },
{ map = "-77,-36", fight = true, path = "top", },
{ map = "-76,-36", fight = true, path = "left", },
{ map = "-75,-36", fight = true, path = "left|bottom", },
{ map = "-74,-36", fight = true, path = "left|bottom", },
{ map = "-73,-36", fight = true, path = "bottom", },
{ map = "-76,-35", fight = true, path = "top", },
{ map = "-75,-35", fight = true, path = "left", },
{ map = "-74,-35", fight = true, path = "bottom", },
{ map = "-73,-35", fight = true, path = "left", },
{ map = "-76,-34", fight = true, path = "right", },
{ map = "-75,-34", fight = true, path = "top", },
{ map = "-74,-34", fight = true, path = "bottom", },
{ map = "-73,-34", fight = true, path = "left", },
{ map = "-76,-33", fight = true, path = "top", },
{ map = "-75,-33", fight = true, path = "left", },
{ map = "-74,-33", fight = true, path = "left", },
{ map = "54172457", fight = true, path = "right" },

  }
end
function bank() 
  return {
   
      {map="88081177",door="216"},
       { map = "99095051", npcBank=true, path = "410" },
      
      {map = "12,8", path = "top"},
      {map = "12,7", path = "top"},
      {map = "13,8", path = "top"},
      {map = "13,7", path = "top"},
      {map = "13,6", path = "top"},
      {map = "12,6", path = "top"},
      {map = "13,5", path = "left"},
      {map = "12,5", path = "left"},
      {map = "11,5", path = "left"},
      {map = "10,5", path = "left"},
      {map = "9,5", path = "left"},
      {map = "8,5", path = "left"},
      {map = "7,5", path = "left"},
      {map = "6,5", path = "left"},
      {map = "5,5", path = "top"},
      {map = "5,4", path = "top"},
      {map = "5,3", path = "top"},
      {map = "5,2", path = "top"},
      {map = "5,1", path = "top"},
      {map = "5,0", path = "left"},
      {map = "4,0", path = "left"},
      {map = "3,0", path = "left"},
      {map = "2,0", path = "top"},
      {map = "2,-1", path = "top"},
    }
end



